version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    environment:
      PYTHONPATH: ~/project_root 
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run test_fertility_rates_forecasting
          command: python -m unittest fertility_rates_forecasting.test_fertility_rate_forecasting
          

workflows:
  version: 2
  build:
    jobs:
      - build
