version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Run test_fertility_rates_forecast
          command: pytest test_fertility_rates_forecast.py
          

workflows:
  version: 2
  build:
    jobs:
      - build
